// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lknjwcbglmfmujjcecgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrbmp3Y2JnbG1mbXVqamNlY2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjQ4NzIsImV4cCI6MjA2Mjg0MDg3Mn0.XOuDPceI-0wVr3Obd95-kbR_pte1YgQjbwC4QkJscmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});